export type CURSOR_POSITION_START = 0;
export type CURSOR_POSITION_MIDDLE = 1;
export type CURSOR_POSITION_END = 2;
export type CURSOR_DIRECTION = CURSOR_POSITION_START | CURSOR_POSITION_MIDDLE | CURSOR_POSITION_END;